version: '3.4'

services:
  nginx:
    image: "nginx:latest"
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    container_name: "am.onetimemessages.webserver"
  web:
    image: ${DOCKER_REGISTRY-}amonetimemessagesweb
    restart: unless-stopped
    build:
      context: .
      dockerfile: src/AM.OneTimeMessages.Web/Dockerfile
    container_name: "am.onetimemessages.web"
  db:
    image: "redis:alpine"
    restart: unless-stopped
    container_name: "am.onetimemessages.data"