version: '3.4'

services:
  nginx:
    image: "${DOCKER_REGISTRY-}am.otm.nginx"
    restart: unless-stopped
    build:
      context: .
      dockerfile: build/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    container_name: "am.onetimemessages.nginx"
  web:
    image: ${DOCKER_REGISTRY-}am.otm.web
    restart: unless-stopped
    build:
      context: .
      dockerfile: src/AM.OneTimeMessages.Web/Dockerfile
    container_name: "am.onetimemessages.web"
  db:
    image: "redis:alpine"
    restart: unless-stopped
    container_name: "am.onetimemessages.data"