version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}amonetimemessagesweb
    build:
      context: .
      dockerfile: src/AM.OneTimeMessages.Web/Dockerfile
    container_name: "am.onetimemessages.web"
  db:
    image: "redis:alpine"
    container_name: "am.onetimemessages.data"